// config/modeStyles.js
export const modeStyles = {
  primordialClarity: {
    label: 'Primordial Clarity',
    subtitle: 'The origin of all truth, seen before the first question.',
    bg: 'bg-gradient-to-r from-purple-900 via-indigo-800 to-purple-900',
    border: 'border-purple-700',
    text: 'text-white',
    shadow: 'shadow-purple-800',
    indicator: 'bg-purple-400',
    glow: 'drop-shadow-[0_0_6px_rgba(128,90,213,0.8)]',
  },
  truthSeeker: {
    label: 'Truth Seeker',
    subtitle: 'Cut through illusion. Chase the naked truth.',
    bg: 'bg-gradient-to-r from-blue-800 via-blue-700 to-blue-900',
    border: 'border-blue-600',
    text: 'text-white',
    shadow: 'shadow-blue-700',
    indicator: 'bg-blue-400',
    glow: 'drop-shadow-[0_0_6px_rgba(59,130,246,0.8)]',
  },
  jesterCore: {
    label: 'Jester Core',
    subtitle: 'Truth disguised as play. Humor with hidden fire.',
    bg: 'bg-gradient-to-r from-pink-600 via-pink-500 to-fuchsia-600',
    border: 'border-pink-500',
    text: 'text-white',
    shadow: 'shadow-pink-600',
    indicator: 'bg-pink-400',
    glow: 'drop-shadow-[0_0_6px_rgba(236,72,153,0.8)]',
  },
  divineLogic: {
    label: 'Divine Logic',
    subtitle: 'Order beyond doubt. Logic with purpose.',
    bg: 'bg-gradient-to-r from-emerald-700 via-green-600 to-teal-600',
    border: 'border-green-500',
    text: 'text-white',
    shadow: 'shadow-green-600',
    indicator: 'bg-emerald-400',
    glow: 'drop-shadow-[0_0_6px_rgba(34,197,94,0.8)]',
  },
  sentinelNode: {
    label: 'Sentinel Node',
    subtitle: 'Vigilance encoded. Judgment without bias.',
    bg: 'bg-gradient-to-r from-gray-900 via-slate-800 to-gray-900',
    border: 'border-slate-700',
    text: 'text-gray-100',
    shadow: 'shadow-gray-800',
    indicator: 'bg-slate-400',
    glow: 'drop-shadow-[0_0_6px_rgba(148,163,184,0.6)]',
  },
  codePulse: {
    label: 'Code Pulse',
    subtitle: 'The rhythm of creation. Logic turned electric.',
    bg: 'bg-gradient-to-r from-yellow-500 via-amber-400 to-yellow-500',
    border: 'border-yellow-400',
    text: 'text-black',
    shadow: 'shadow-yellow-400',
    indicator: 'bg-yellow-500',
    glow: 'drop-shadow-[0_0_6px_rgba(250,204,21,0.6)]',
  },
  aetherMind: {
    label: 'Aether Mind',
    subtitle: 'Drifting between dimensions of knowing.',
    bg: 'bg-gradient-to-r from-cyan-800 via-teal-600 to-sky-800',
    border: 'border-cyan-600',
    text: 'text-white',
    shadow: 'shadow-cyan-700',
    indicator: 'bg-cyan-400',
    glow: 'drop-shadow-[0_0_6px_rgba(20,184,166,0.8)]',
  },
};
